architect:
  - dgroup

readers:
  - "urn:github:1651114"

assets:
  settings.xml: "dgroup/ossrh#settings.xml"
  pubring.gpg:  "dgroup/ossrh#1B112A24-term4j-pubring.gpg"
  secring.gpg:  "dgroup/ossrh#1B112A24-term4j-secring.gpg"

merge:
  env:
      MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Dpropof=10 -Pqulice clean package
release:
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git add pom.xml
    git commit -am "$tag"
    mvn -X -V -Dgpg.homedir="$HOME" -Dpropof=10 -P qulice,ossrh-term4j -s ../settings.xml clean deploy